### ISSUE TITLE
Invalid ticker amongst valid tickers in get_data results in Error message since version 1.1.0

### ISSUE THREAD

**Issue by quantc0d32** [DatastreamDSWS/Datastream#13]
Hello, 

I experienced above issue in version 1.1.0 which hasn't been there in version 1.0.9.

This is the request which leads to the error: 
`ds.get_data('AU000000EVN4, AU000000FNP3', 'X', '2021-11-23')`

As there is no data for `AU000000FNP3`, in version 1.0.9 above request resulted in a DataFrame with prices for `AU000000EVN4` and a column of `None` for `AU000000FNP3`.  In version 1.1.0 the error message below occurs.

I got rid of the error by switching back to version 1.0.9, but thought this might be of interest for you.

Thanks & Regards
Kilian

**..and this is the error message:**

```
get_data : Exception Occured
(<class 'ValueError'>, ValueError('Item must have length equal to number of levels.'), <traceback object at 0x0000018A51FC7E40>)
None

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: ' AU000000FNP3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pandas\core\frame.py", line 3751, in _set_item_mgr
    loc = self._info_axis.get_loc(key)
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pandas\core\indexes\multi.py", line 2959, in get_loc
    mask = self.codes[i][loc] == self._get_loc_single_level_index(
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pandas\core\indexes\multi.py", line 2855, in _get_loc_single_level_index
    return level_index.get_loc(key)
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: ' AU000000FNP3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\DatastreamDSWS\DS_Response.py", line 160, in get_data
    response_dataframe = self._format_Response(json_Response['DataResponse'])
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\DatastreamDSWS\DS_Response.py", line 462, in _format_Response
    dataframe = self._get_DatatypeValues(response_json)
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\DatastreamDSWS\DS_Response.py", line 382, in _get_DatatypeValues
    df[colNames] = None
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pandas\core\frame.py", line 3612, in __setitem__
    self._set_item(key, value)
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pandas\core\frame.py", line 3797, in _set_item
    self._set_item_mgr(key, value)
ValueError: Item must have length equal to number of levels.


```

**Comment by DatastreamDSWS** [comment]
Hi Kilian, 

This issue was due to null currency for some instruments. This has been fixed now. The currency displayed will be 'NA' in case of null currency, instead of exceptions while uploading data to dataframe. I have uploaded the new version 1.0.10. Please check.

Thanks,
Datastream DSWS

**Comment by quantc0d32** [comment]
perfect, thank you! 
I can confirm the request works fine now!

Regards
Kilian
