### ISSUE TITLE
Exception("Invalid JSON Date")

### ISSUE THREAD

**Issue by jirapongse-refinitiv** [DatastreamDSWS/Datastream#7]
The client found "Exception("Invalid JSON Date")" when running the below code:

```
GDP = ds.get_data(tickers='USCGDP..D', 
                  fields='X', 
                  start='1999-12-31', 
                  end='2003-12-31', 
                  freq='Q')
```

```
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\DatastreamDSWS\DS_Response.py", line 299, in _get_Date
    raise Exception("Invalid JSON Date")
Exception: Invalid JSON Date
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\DatastreamDSWS\DS_Response.py", line 299, in _get_Date
    raise Exception("Invalid JSON Date")
Exception: Invalid JSON Date
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\DatastreamDSWS\DS_Response.py", line 299, in _get_Date
    raise Exception("Invalid JSON Date")
Exception: Invalid JSON Date
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\DatastreamDSWS\DS_Response.py", line 299, in _get_Date
    raise Exception("Invalid JSON Date")
Exception: Invalid JSON Date
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\DatastreamDSWS\DS_Response.py", line 299, in _get_Date
    raise Exception("Invalid JSON Date")
Exception: Invalid JSON Date
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\DatastreamDSWS\DS_Response.py", line 299, in _get_Date
    raise Exception("Invalid JSON Date")
Exception: Invalid JSON Date
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\DatastreamDSWS\DS_Response.py", line 299, in _get_Date
    raise Exception("Invalid JSON Date")
Exception: Invalid JSON Date
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\DatastreamDSWS\DS_Response.py", line 299, in _get_Date
    raise Exception("Invalid JSON Date")
Exception: Invalid JSON Date
```

However, after downgrading to 1.0.2, it works fine.

**Comment by DatastreamDSWS** [comment]
Hi Jirapongse,

I am working on this issue. I shall fix this in the next version.

**Comment by DatastreamDSWS** [comment]
Hi Jirapongse,

Please install the new package (version 1.0.7) and check.

**Comment by linusgvr** [comment]
Hi,

I have below queries:
1. How to get complete Data for each Symbol without passing Start Date? 
2. How to get Frequency / Data Type/Unit Information along with Data or any separate API to get these Metadata?

**Comment by Jbr1ght** [comment]
Hi, Please raise these quries to the Refinitiv helpdesk. This is pertaining to the product rather than the Python library. Best regards

James

**Comment by linusgvr** [comment]
Hi Team,

For me two Datastream Expression giving Trouble. i.e USREFAPT, PCH#(USREFAPT,1y), when I pass only these two I am getting Values; but if I pass with other symbols result is None.

DSR = DSDSWS.Datastream(username='Datastream_Username', password='Datastream_Password')

Tickers = 'USREFAPT, PCH#(USREFAPT,1y)'
Data = DSR.get_data(tickers=Tickers, fields=None, start='1950-01-01', freq='Q', kind=1)
-- Here I will get the Data

Tickers = 'USHOUSE.O-USPVH1UNE,PCH#(USHOUSE.O-USPVH1UNE,1y),USVACAPTR,USREFAPT,PCH#(USREFAPT,1y)'
Data = DSR.get_data(tickers=Tickers, fields=None, start='1950-01-01', freq='Q', kind=1)
But for USREFAPT, PCH#(USREFAPT,1y) Data is None

Please let me whats wrong with this?

**Comment by DatastreamDSWS** [comment]
> Hi,
> 
> I have below queries:
> 
> 1. How to get complete Data for each Symbol without passing Start Date?
> 2. How to get Frequency / Data Type/Unit Information along with Data or any separate API to get these Metadata?

Hi Linusgvr,

Please refer the document on how to get the Instrument Names and the Datatype names (with or without passing the StartDate)
Frequency and Unit information retrieval  - Change has not been done. I shall get back on this.
